## Installation Instructions

    pip install numpy



## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

# Numpy Arrays

• Array is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

• NumPy’s array class is called ndarray. It is also known by the alias array.

• NumPy supports multidimensional arrays over which you can easily apply mathematical operations.

• It executes computations and mathematical calculations in an element-wise manner.

## Creating NumPy Arrays

### From a Python List , Tuples 

We can create an array by directly converting a list or list of lists:

In [2]:
li = [5,8,9,4,7,9]
tu = (5,8,9,4,7,9)

In [3]:
arr = np.array(li)
arr

array([5, 8, 9, 4, 7, 9])

In [4]:
print(arr)

[5 8 9 4 7 9]


In [5]:
arr = np.array(tu)
arr 

array([5, 8, 9, 4, 7, 9])

In [6]:
nested_list = [ [25,65] , [6,8] , [32,26] ] 
nested_list

[[25, 65], [6, 8], [32, 26]]

In [7]:
mat = np.array(nested_list)
print(mat)

[[25 65]
 [ 6  8]
 [32 26]]


In [8]:
print(type(mat))

<class 'numpy.ndarray'>


### Checking the dimesnions of a array

In [9]:
mat.ndim

2

### Checking the size of a array

In [10]:
mat.size

6

### Checking the data type of a array

In [11]:
mat.dtype

dtype('int64')

### Checking the shape of a array

In [12]:
mat

array([[25, 65],
       [ 6,  8],
       [32, 26]])

In [13]:
mat.shape

(3, 2)

## Built-in Methods

ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

numpy.arange( start(default = 0) , stop , step(default = 1) )

If `step` is specified as a position argument, `start` must also be given.

In [14]:
arr = np.arange(0, 299.5, 0.9, dtype='byte')
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [15]:
np.eye(4).dtype

dtype('float64')

In [16]:
arr.dtype

dtype('int8')

In [17]:
print(np.arange(0.5 , 30.5 , 0.36))

[ 0.5   0.86  1.22  1.58  1.94  2.3   2.66  3.02  3.38  3.74  4.1   4.46
  4.82  5.18  5.54  5.9   6.26  6.62  6.98  7.34  7.7   8.06  8.42  8.78
  9.14  9.5   9.86 10.22 10.58 10.94 11.3  11.66 12.02 12.38 12.74 13.1
 13.46 13.82 14.18 14.54 14.9  15.26 15.62 15.98 16.34 16.7  17.06 17.42
 17.78 18.14 18.5  18.86 19.22 19.58 19.94 20.3  20.66 21.02 21.38 21.74
 22.1  22.46 22.82 23.18 23.54 23.9  24.26 24.62 24.98 25.34 25.7  26.06
 26.42 26.78 27.14 27.5  27.86 28.22 28.58 28.94 29.3  29.66 30.02 30.38]


## Random 

It is used to create random number arrays:

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).
- can be used for genrating random numbers for authentication
- lottery numbers

In [18]:
np.random.randint(1,40)

6

In [19]:
np.random.randint(100000,1000000)

962817

In [20]:
np.random.randint(1,4000,10)

array([2985, 1318, 2953,  930, 2623, 3522, 1993, 1778, 1978, 1416])

In [21]:
np.random.randint(1 , 100 , size = (5, 2) )

array([[87, 72],
       [11, 84],
       [39, 53],
       [59, 66],
       [87, 62]])

## Reshape
Returns an array containing the same data with a new shape.

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr.reshape(5, 2)  

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = arr.reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
arr1 = arr.reshape(10, 3)  # 3,10   10,3  15,2  2,15   30,1  1,30  5,6   6,5

arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [29]:
arr1.T  # or arr1.transpose()

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29]])

In [30]:
len(arr1)

10

In [31]:
arr1.size

30

### Flatten
We can use flatten method to get a copy of array collapsed into one dimension.

In [32]:
arr = np.random.randint(1,400 , (3,5)) 

In [33]:
arr

array([[ 70, 129, 109, 152, 177],
       [249, 104, 240,  60,  84],
       [ 87,  87, 192, 239, 261]])

In [34]:
arr1 = arr.flatten() # ravel()
arr1

array([ 70, 129, 109, 152, 177, 249, 104, 240,  60,  84,  87,  87, 192,
       239, 261])

In [35]:
arr1.shape

(15,)

In [36]:
len(arr1)

15

In [37]:
arr.dtype

dtype('int64')

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [38]:
ranarr = np.random.randint(0,50,10)
ranarr

array([25,  5, 18, 41, 49, 49,  6, 49, 22, 30])

In [39]:
# gives the maximum value
ranarr.max()

np.int64(49)

In [40]:
# gives the maximum value index
ranarr.argmax()

np.int64(4)

In [41]:
# gives the maximum value
ranarr.min()

np.int64(5)

In [42]:
# gives the minummum value index
ranarr.argmin()

np.int64(1)

# Indexing and Selection


In [43]:
#Creating sample array
arr = np.random.randint(0,50,10)

In [44]:
arr

array([ 0, 12, 17,  1, 47,  3, 13, 24, 45, 36])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [45]:
#Get a value at an index
arr[8]

np.int64(45)

In [46]:
arr[-1] 

np.int64(36)

In [47]:
# Get values in a range
arr[1:5:2] 

array([12,  1])

In [48]:
#Get values in a range
arr[:5]

array([ 0, 12, 17,  1, 47])

## Updating Array By Index

Numpy arrays differ from list because of their ability to change multiple values with index.

In [49]:
arr

array([ 0, 12, 17,  1, 47,  3, 13, 24, 45, 36])

In [50]:
arr[6]

np.int64(13)

In [51]:
# updating array by index
arr[6] = 1
arr

array([ 0, 12, 17,  1, 47,  3,  1, 24, 45, 36])

In [52]:
arr[0:5]

array([ 0, 12, 17,  1, 47])

In [53]:
# Setting a value with index range 
arr[0:5] = 100 # not possible with list
arr

array([100, 100, 100, 100, 100,   3,   1,  24,  45,  36])

In [54]:
# defining array ones again
arr = np.arange(0,15)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [57]:
#Important notes on Slices
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
#Change Slice
slice_of_arr[:] = 56

slice_of_arr

array([56, 56, 56, 56, 56, 56])

In [59]:
arr

array([56, 56, 56, 56, 56, 56,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
#To get a copy, need to be explicit
arr = np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
slice_of_arr = arr[0:6].copy()

In [62]:
slice_of_arr[:] = 56
slice_of_arr

array([56, 56, 56, 56, 56, 56])

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**(Recommended). 

In [64]:
arr_2d = np.array( [  [78,97,24]  ,   [25,1,23]  ,     [9,4,2]  ]  )

#Show
arr_2d

array([[78, 97, 24],
       [25,  1, 23],
       [ 9,  4,  2]])

In [65]:
#Indexing row
arr_2d[1]

array([25,  1, 23])

In [66]:
# Format is arr_2d[row][col] or arr_2d[row,col]   , index are passed for row and column

# Getting individual element value
arr_2d[0][0]

np.int64(78)

In [67]:
arr_2d[0 , 0]

np.int64(78)

In [68]:
# arr_2d[row,col] method
arr_2d[1,2]

np.int64(23)

In [69]:
arr_2d

array([[78, 97, 24],
       [25,  1, 23],
       [ 9,  4,  2]])

In [70]:
#Shape (2,2) from top right corner

arr_2d[:2, 1:] 

array([[97, 24],
       [ 1, 23]])

In [71]:
#Shape bottom row  - arr_2d[row][col]
arr_2d[2]

array([9, 4, 2])

In [72]:
#Shape bottom row  -  arr_2d[row,col] method
arr_2d[2, :]

array([9, 4, 2])

In [73]:
ar = np.random.randint(10,1000, size = (10,4))

In [74]:
ar

array([[267, 649, 213, 708],
       [317, 808,  76, 206],
       [993, 423, 567, 789],
       [143,  46,  85, 315],
       [346, 224, 424, 440],
       [354, 147, 363, 826],
       [737, 104, 698, 297],
       [737, 232, 839, 946],
       [257, 734, 692, 986],
       [561, 744, 430, 975]])

In [75]:
ar[3:7  , 1:]

array([[ 46,  85, 315],
       [224, 424, 440],
       [147, 363, 826],
       [104, 698, 297]])

## comparison operators.

In [76]:
arr = np.arange(14,34)
arr

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33])

In [77]:
print(arr > 24)

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True]


In [78]:
print(type(arr > 24))

<class 'numpy.ndarray'>


In [79]:
arr

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33])

In [80]:
arr[arr > 24]  #  this is indexing

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

In [81]:
bool_arr = arr > 24

In [82]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [83]:
#  returns elements where the value is True.
arr[bool_arr]

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

In [84]:
x = 24
arr[arr > x]

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

In [85]:
print(arr)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]


# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [86]:
arr = np.arange(0,10)
arr1 = np.arange(30,40)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [89]:
arr + arr1

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [90]:
arr * arr1

array([  0,  31,  64,  99, 136, 175, 216, 259, 304, 351])

In [91]:
arr - arr1

array([-30, -30, -30, -30, -30, -30, -30, -30, -30, -30])

In [92]:
arr / arr1

array([0.        , 0.03225806, 0.0625    , 0.09090909, 0.11764706,
       0.14285714, 0.16666667, 0.18918919, 0.21052632, 0.23076923])

In [93]:
# Also warning, but not an error instead infinity
1/arr1

array([0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103])

In [94]:
# Also warning, but not an error instead infinity
1/arr

/tmp/ipykernel_1840968/1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
print(arr ** 3)

[  0   1   8  27  64 125 216 343 512 729]


### Concat

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr1

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [99]:
arr2by2 = np.eye(2)
arr2by1 = np.array([[1], [1]])
print(arr2by2.shape)
print(arr2by1.shape)
print(np.hstack((arr2by2, arr2by1)).shape)


(2, 2)
(2, 1)
(2, 3)


In [100]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 3], [8, 2]])
print(arr1.dot(arr2))


[[21  7]
 [47 17]]


In [101]:
np.hstack( (arr2by1 , arr1)  )

array([[1, 1, 2],
       [1, 3, 4]])

In [102]:
np.vstack(  (arr2by2 , arr1)  )

array([[1., 0.],
       [0., 1.],
       [1., 2.],
       [3., 4.]])

#### Dot prod

In [103]:
x = np.array( [ [1,2] , [ 3,4] ])
y = np.array( [ [5,3] , [ 8,2] ])

In [104]:
x

array([[1, 2],
       [3, 4]])

In [105]:
y

array([[5, 3],
       [8, 2]])

In [106]:
np.dot(x,y)

array([[21,  7],
       [47, 17]])

In [107]:
x @ y

array([[21,  7],
       [47, 17]])

In [108]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([3, 4, 5])
print(vec1 @ vec2)

26


## Broadcasting

1. NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array. 

2. However, broadcasting does have its own limitations. It is subject to certain constraints as listed here:
    1. When NumPy operates on two arrays, it compares their shapes element-wise. It finds these shapes compatible only if:
                     - Their dimensions are the same, or
                     - One of them has a dimension of size 1
    2. If these conditions are not met, a "ValueError” is thrown, indicating that the arrays have incompatible shapes!
    
3. Broadcasting is possible if the following rules are satisfied 
    1. Array with smaller ndim than the other is prepended with '1' in its shape.
    2. Size in each dimension of the output shape is maximum of the input sizes in that dimension.

In [109]:
a = np.array([  [0,0,0] ,  [10,10,10] , [20,20,20] , [30,30,30] ]) 
b = np.array( [1,2,3] ) 

In [110]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [111]:
b

array([1, 2, 3])

In [112]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [113]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([3]) 

In [114]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [115]:
b

array([3])

In [116]:
a + b

array([[ 3,  3,  3],
       [13, 13, 13],
       [23, 23, 23],
       [33, 33, 33]])

In [117]:
c = np.array( [[ 1,2,3 ] , [3,4,5] ])

In [118]:
c

array([[1, 2, 3],
       [3, 4, 5]])

In [119]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [120]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

## Adding of Diagonals

In [121]:
a = np.array([[3,1],[1,1]])

In [122]:
a

array([[3, 1],
       [1, 1]])

In [123]:
np.trace(a)

np.int64(4)

## Universal Array Functions

Numpy comes with many [universal array functions](https://numpy.org/doc/stable/reference/routines.math.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

works with list , tuples as well

In [124]:
arr = np.arange(1,11)

In [125]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [127]:
#Calcualting product
print(np.prod(arr))

3628800


In [128]:
#Calcualting mean
print(np.mean(arr))  # #same as arr.mean()

5.5


In [129]:
#Calcualting Standard Deviation
np.std(arr)

np.float64(2.8722813232690143)

In [130]:
#Calcualting Square
np.square(arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [131]:
np.max(arr) #same as arr.max()

np.int64(10)

In [132]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [133]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [134]:
# Array element from first array (arr1) is raised to the power of element from second element (arr2)(all happens element-wise).
# Both arr1 and arr2 must have same shape and each element in arr1 must be raised to corresponding +ve value from arr2.

arr1 = [2, 2, 2, 2, 2] 
arr2 = [2, 3, 4, 5, 6] 
np.power(arr1, arr2)  # arr2 is the exponent

# https://numpy.org/doc/stable/reference/ufuncs.html#universal-functions-ufunc

array([ 4,  8, 16, 32, 64])